### PR TITLE
Improved error reporting and version ordering

### PR DESCRIPTION
**Pull request by mwanji**
@jamesward this might merit a 0.1.0 release. Here's what Sonatype's guide says about allowing another user to publish:

> How does a new user ask for publish rights to existing repositories
> Follow step 2, sign up and then leave a comment on the JIRA ticket with the username. We will assign related roles to him and update the ticket.

So maybe you have to do the first release, then create a ticket to ask them to allow me to release the artifact? My username there is mwanji.

Note: In the commit message about sisu-guice, I meant sisu-guava

### CODE REVIEW

**Comment by huntc** [comment]
Hey @mwanji It'd be great in future if you'd let others review and merge your PRs. This has probably not been discussed, but its a good rule in general. Thanks.

**Comment by huntc** [comment]
No tests?

**Comment by mwanji** [comment]
Ok. I wanted to get it to a state where it was interesting enough for someone to use. I think it is now, so I won't auto-merge in the future.

Re: tests, I admit I was lazy about learning how to unit test maven plugins. I'll add some.

**Comment by huntc** [comment]
Thanks @mwanji Happy to help out where I can here too - I've written plenty of Maven plugins in my time!

**Comment by mwanji** [comment]
Cool! Quick question: for easier testing, is it generally best to make the plugin a shell that delegates to Maven-agnostic classes, or are the testing utilities good enough not to do that?

**Comment by huntc** [comment]
I would unit test without Maven concerns using Mockito and JUnit. I've actually not written integration tests for plugins though, I guess I've never deemed it that necessary. However this may help that:

http://maven.apache.org/plugin-testing/maven-plugin-testing-harness/

...and it probably is a good idea. :-)

The Codehaus Mojo project is always a good source of inspiration for this kind of thing.

**Comment by jamesward** [comment]
Sorry for the delay.  I've requested access: https://issues.sonatype.org/browse/OSSRH-6813

**Comment by mwanji** [comment]
No problem. Thanks a lot!

**Pull request merged**
